Create frontend
yuzinu/howler pull request #5
Opened 2023-03-22 21:08 UTC by KJMoon

Set up the frontend, with react and webpack, to connect with the backend. Also configured the backend to include nodemon.

2023-03-22 21:14 UTC, yuzinu requested changes
Great job! 🙌 Looks like we can start getting into the nitty gritty!

2023-03-22 21:14 UTC, yuzinu commented on backend/Dockerfile
> +# RUN npm install --save-dev nodemon
We can remove this line

2023-03-23 01:03 UTC, KJMoon commented on backend/Dockerfile
> +# RUN npm install --save-dev nodemon
Removed the line

2023-03-23 02:17 UTC, yuzinu approved these changes
LGTM! 🙌

2023-03-23 02:27 UTC, merged